name: Static Code Checks

on:
  push:
  pull_request:
  schedule:
    - cron: "0 4 * * *"

  workflow_dispatch:

jobs:
  checks:
    env:
      src: "lazy_imports"
      test-src: "tests"
      other-src: "setup.py"

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: |
          python -m pip install -U pip
          pip install --progress-bar off -U .[checking,optional]

      - name: Check with pydocstyle
        run: pydocstyle --count ${{ env.src }} ${{ env.other-src }}

      - name: Check with black
        run: black ${{ env.src }} ${{ env.test-src }} ${{ env.other-src }} --check --diff

      - name: Check with flake8
        run: flake8 ${{ env.src }} ${{ env.other-src }}

      - name: Check with isort
        run: isort ${{ env.src }} ${{ env.test-src }} ${{ env.other-src }} --check --diff

      - name: Check with mdformat
        run: mdformat --check *.md

      - name: Check with mypy
        run: mypy --install-types --non-interactive ${{ env.src }} ${{ env.other-src }}

      - name: Check with pylint
        run: pylint ${{ env.src }}
